# Generated by Django 3.1.2 on 2021-04-19 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_collections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='create_date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='productcollectionposition',
            old_name='Collection',
            new_name='collection',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='update_date',
        ),
        migrations.AddField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
