# Generated by Django 3.1.2 on 2021-04-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210419_1813'),
        ('reviews', '0002_auto_20210419_1813'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
